import React, { useState } from 'react';
import Header from '../components/Header';
import MatchCard from '../components/MatchCard';
import BottomNav from '../components/BottomNav';
import { Users, Trophy, Target, Percent } from 'lucide-react';

const Dashboard = () => {
  const [user] = useState({
      pseudo: "Zephyr",
          uid: "demo123",
              avatar: "https://i.pravatar.cc/44?u=demo123"
                });

                  const nextMatch = {
                      type: "Scrim",
                          date: "12 Juillet",
                              heure: "20:30",
                                  adversaire: "Team Phoenix",
                                      arene: "Summoner's Rift"
                                        };

                                          const stats = [
                                              { label: "Joueurs", value: 7, icon: Users },
                                                  { label: "Scrims", value: 24, icon: Target },
                                                      { label: "Présence", value: "92%", icon: Percent },
                                                          { label: "Victoires", value: "68%", icon: Trophy },
                                                            ];

                                                              const playersOnline = [
                                                                  { pseudo: "Zephyr", status: "En ligne" },
                                                                      { pseudo: "Karma", status: "En ligne" },
                                                                          { pseudo: "Shadow", status: "En jeu" },
                                                                            ];

                                                                              const announcements = [
                                                                                  {
                                                                                        id: 1,
                                                                                              title: "Entraînement individuel",
                                                                                                    author: "Coach Alex",
                                                                                                          date: "Il y a 2h",
                                                                                                                description: "Focus sur le mid lane ce soir à 19h."
                                                                                                                    }
                                                                                                                      ];

                                                                                                                        return (
                                                                                                                            <div style={{ paddingBottom: '90px' }}>
                                                                                                                                  <Header user={user} />

                                                                                                                                        <div style={{ padding: '0 20px' }}>
                                                                                                                                                {/* Prochain Scrim */}
                                                                                                                                                        <div style={{ marginBottom: '32px' }}>
                                                                                                                                                                  <div className="section-title">Prochain scrim</div>
                                                                                                                                                                            <MatchCard match={nextMatch} onView={() => {}} />
                                                                                                                                                                                    </div>

                                                                                                                                                                                            {/* Statistiques */}
                                                                                                                                                                                                    <div style={{ marginBottom: '32px' }}>
                                                                                                                                                                                                              <div className="section-title">Statistiques</div>
                                                                                                                                                                                                                        <div style={{ 
                                                                                                                                                                                                                                    display: 'grid', 
                                                                                                                                                                                                                                                gridTemplateColumns: 'repeat(2, 1fr)', 
                                                                                                                                                                                                                                                            gap: '12px' 
                                                                                                                                                                                                                                                                      }}>
                                                                                                                                                                                                                                                                                  {stats.map((stat, index) => {
                                                                                                                                                                                                                                                                                                const Icon = stat.icon;
                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                              <div key={index} className="stat-card">
                                                                                                                                                                                                                                                                                                                                                <Icon size={22} color="#D4AF37" style={{ marginBottom: '8px' }} />
                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontSize: '28px', fontWeight: 800 }}>{stat.value}</div>
                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ fontSize: '13px', color: 'var(--grey)' }}>{stat.label}</div>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                              })}
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Joueurs connectés */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ marginBottom: '32px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="section-title">Joueurs connectés</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="glass-card" style={{ padding: '16px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {playersOnline.map((player, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={index} style={{ 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              display: 'flex', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alignItems: 'center', 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              gap: '14px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              padding: '10px 0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderBottom: index !== playersOnline.length - 1 ? '1px solid #252525' : 'none'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <img 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              src={`https://i.pravatar.cc/36?u=${player.pseudo}`} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alt={player.pseudo}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="avatar" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{ width: 36, height: 36 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontWeight: 600 }}>{player.pseudo}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontSize: '12px', color: 'var(--grey)' }}>{player.status}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* Annonces */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="section-title">Dernières annonces</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {announcements.map((ann, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={index} className="glass-card" style={{ padding: '20px', marginBottom: '12px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontWeight: 700, fontSize: '16px' }}>{ann.title}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ color: 'var(--grey)', fontSize: '13px', marginTop: '4px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {ann.author} • {ann.date}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ marginTop: '12px', lineHeight: 1.5, color: '#ccc' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {ann.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <BottomNav />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default Dashboard;