import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';

const Login = () => {
  const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
      const [loading, setLoading] = useState(false);
        const navigate = useNavigate();

          const handleLogin = async (e) => {
              e.preventDefault();
                  setLoading(true);

                      // Simulation de connexion
                          setTimeout(() => {
                                localStorage.setItem('user', JSON.stringify({ 
                                        email, 
                                                pseudo: email.split('@')[0] 
                                                      }));
                                                            navigate('/');
                                                                }, 500);
                                                                  };

                                                                    return (
                                                                        <div style={{ padding: '40px 24px', minHeight: '100vh' }}>
                                                                              <div style={{ textAlign: 'center', marginBottom: '48px' }}>
                                                                                      <div style={{ 
                                                                                                width: 72, 
                                                                                                          height: 72, 
                                                                                                                    background: 'var(--gold)', 
                                                                                                                              borderRadius: '20px', 
                                                                                                                                        margin: '0 auto 20px',
                                                                                                                                                  display: 'flex',
                                                                                                                                                            alignItems: 'center',
                                                                                                                                                                      justifyContent: 'center',
                                                                                                                                                                                fontSize: '36px',
                                                                                                                                                                                          fontWeight: 800,
                                                                                                                                                                                                    color: '#090909'
                                                                                                                                                                                                            }}>
                                                                                                                                                                                                                      D
                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                      <h1 style={{ fontSize: '32px', margin: 0 }}>DYNO Manager</h1>
                                                                                                                                                                                                                                              <p style={{ color: 'var(--grey)', marginTop: '8px' }}>Connexion à votre équipe</p>
                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                          <form onSubmit={handleLogin}>
                                                                                                                                                                                                                                                                  <div style={{ marginBottom: '20px' }}>
                                                                                                                                                                                                                                                                            <label style={{ display: 'block', marginBottom: '8px', fontSize: '14px', color: 'var(--grey)' }}>Email</label>
                                                                                                                                                                                                                                                                                      <input 
                                                                                                                                                                                                                                                                                                  type="email" 
                                                                                                                                                                                                                                                                                                              className="input" 
                                                                                                                                                                                                                                                                                                                          value={email} 
                                                                                                                                                                                                                                                                                                                                      onChange={(e) => setEmail(e.target.value)} 
                                                                                                                                                                                                                                                                                                                                                  required 
                                                                                                                                                                                                                                                                                                                                                              placeholder="ton@email.com"
                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ marginBottom: '32px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                  <label style={{ display: 'block', marginBottom: '8px', fontSize: '14px', color: 'var(--grey)' }}>Mot de passe</label>
                                                                                                                                                                                                                                                                                                                                                                                                            <input 
                                                                                                                                                                                                                                                                                                                                                                                                                        type="password" 
                                                                                                                                                                                                                                                                                                                                                                                                                                    className="input" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                value={password} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setPassword(e.target.value)} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        required 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    placeholder="••••••••"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="submit" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="btn btn-primary" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={{ width: '100%', padding: '16px' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading ? 'Connexion...' : 'Se connecter'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ textAlign: 'center', marginTop: '24px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link to="/register" style={{ color: 'var(--gold)', textDecoration: 'none' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Pas encore de compte ? S’inscrire
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default Login;