import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';

const Register = () => {
  const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
      const [pseudo, setPseudo] = useState('');
        const [loading, setLoading] = useState(false);
          const navigate = useNavigate();

            const handleRegister = async (e) => {
                e.preventDefault();
                    setLoading(true);

                        setTimeout(() => {
                              localStorage.setItem('user', JSON.stringify({ 
                                      email, 
                                              pseudo: pseudo || email.split('@')[0] 
                                                    }));
                                                          navigate('/');
                                                              }, 500);
                                                                };

                                                                  return (
                                                                      <div style={{ padding: '40px 24px', minHeight: '100vh' }}>
                                                                            <div style={{ textAlign: 'center', marginBottom: '40px' }}>
                                                                                    <div style={{ 
                                                                                              width: 72, 
                                                                                                        height: 72, 
                                                                                                                  background: 'var(--gold)', 
                                                                                                                            borderRadius: '20px', 
                                                                                                                                      margin: '0 auto 20px',
                                                                                                                                                display: 'flex',
                                                                                                                                                          alignItems: 'center',
                                                                                                                                                                    justifyContent: 'center',
                                                                                                                                                                              fontSize: '36px',
                                                                                                                                                                                        fontWeight: 800,
                                                                                                                                                                                                  color: '#090909'
                                                                                                                                                                                                          }}>
                                                                                                                                                                                                                    D
                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                    <h1 style={{ fontSize: '28px', margin: 0 }}>Créer un compte</h1>
                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                <form onSubmit={handleRegister}>
                                                                                                                                                                                                                                                        <div style={{ marginBottom: '20px' }}>
                                                                                                                                                                                                                                                                  <label style={{ display: 'block', marginBottom: '8px', fontSize: '14px', color: 'var(--grey)' }}>Pseudo</label>
                                                                                                                                                                                                                                                                            <input 
                                                                                                                                                                                                                                                                                        type="text" 
                                                                                                                                                                                                                                                                                                    className="input" 
                                                                                                                                                                                                                                                                                                                value={pseudo} 
                                                                                                                                                                                                                                                                                                                            onChange={(e) => setPseudo(e.target.value)} 
                                                                                                                                                                                                                                                                                                                                        required 
                                                                                                                                                                                                                                                                                                                                                    placeholder="TonPseudo"
                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                                                                              <div style={{ marginBottom: '20px' }}>
                                                                                                                                                                                                                                                                                                                                                                                        <label style={{ display: 'block', marginBottom: '8px', fontSize: '14px', color: 'var(--grey)' }}>Email</label>
                                                                                                                                                                                                                                                                                                                                                                                                  <input 
                                                                                                                                                                                                                                                                                                                                                                                                              type="email" 
                                                                                                                                                                                                                                                                                                                                                                                                                          className="input" 
                                                                                                                                                                                                                                                                                                                                                                                                                                      value={email} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) => setEmail(e.target.value)} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                              required 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ marginBottom: '32px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <label style={{ display: 'block', marginBottom: '8px', fontSize: '14px', color: 'var(--grey)' }}>Mot de passe</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        type="password" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="input" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={password} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={(e) => setPassword(e.target.value)} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        required 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="submit" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="btn btn-primary" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ width: '100%', padding: '16px' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {loading ? 'Création...' : 'Créer mon compte'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ textAlign: 'center', marginTop: '24px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link to="/login" style={{ color: 'var(--gold)', textDecoration: 'none' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Déjà un compte ? Se connecter
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default Register;