import React from 'react';
import { Calendar, Clock } from 'lucide-react';
import { motion } from 'framer-motion';

const MatchCard = ({ match, onView }) => {
  if (!match) {
      return (
            <div className="glass-card" style={{ padding: '28px', textAlign: 'center' }}>
                    <div style={{ 
                              width: 64, 
                                        height: 64, 
                                                  background: 'var(--surface)', 
                                                            borderRadius: '9999px',
                                                                      display: 'flex',
                                                                                alignItems: 'center',
                                                                                          justifyContent: 'center',
                                                                                                    margin: '0 auto 20px'
                                                                                                            }}>
                                                                                                                      <Calendar size={28} color="#9A9A9A" />
                                                                                                                              </div>
                                                                                                                                      <div style={{ fontWeight: 600, fontSize: '17px' }}>Aucun scrim prévu</div>
                                                                                                                                              <div style={{ color: 'var(--grey)', marginTop: '6px', fontSize: '14px' }}>
                                                                                                                                                        Créez votre prochain match
                                                                                                                                                                </div>
                                                                                                                                                                      </div>
                                                                                                                                                                          );
                                                                                                                                                                            }

                                                                                                                                                                              return (
                                                                                                                                                                                  <motion.div 
                                                                                                                                                                                        whileHover={{ scale: 1.01 }}
                                                                                                                                                                                              className="glass-card" 
                                                                                                                                                                                                    style={{ padding: '24px' }}
                                                                                                                                                                                                        >
                                                                                                                                                                                                              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                <div style={{ 
                                                                                                                                                                                                                                            display: 'inline-block', 
                                                                                                                                                                                                                                                        background: 'var(--gold)', 
                                                                                                                                                                                                                                                                    color: '#090909', 
                                                                                                                                                                                                                                                                                fontSize: '12px', 
                                                                                                                                                                                                                                                                                            fontWeight: 700, 
                                                                                                                                                                                                                                                                                                        padding: '2px 10px', 
                                                                                                                                                                                                                                                                                                                    borderRadius: '9999px',
                                                                                                                                                                                                                                                                                                                                marginBottom: '12px'
                                                                                                                                                                                                                                                                                                                                          }}>
                                                                                                                                                                                                                                                                                                                                                      {match.type}
                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                          <div style={{ fontSize: '21px', fontWeight: 700 }}>{match.adversaire}</div>
                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ color: 'var(--grey)', marginTop: '2px' }}>{match.arene}</div>
                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                            <div style={{ textAlign: 'right' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', alignItems: 'center', gap: '6px', justifyContent: 'flex-end' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <Clock size={16} />
                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ fontWeight: 600 }}>{match.heure}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ fontSize: '13px', color: 'var(--grey)' }}>{match.date}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => onView(match)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="btn btn-primary" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ marginTop: '24px', width: '100%' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Voir les détails
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default MatchCard;